# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- if .Values.connectivity.networkPolicy.enabled }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "ditto.fullname" . }}-connectivity
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}-connectivity
{{ include "ditto.labels" . | indent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ditto.name" . }}-connectivity
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow inner cluster communication
  - from:
    - podSelector:
        matchLabels:
          actorSystemName: {{ .Values.akka.actorSystemName }}
    ports:
    - protocol: TCP
      port: {{ .Values.akka.remoting.port }}
    - protocol: TCP
      port: {{ .Values.akka.mgmthttp.port }}
  # Open all egress
  egress:
  - {}
{{- end }}
