# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- if .Values.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $name := include "ditto.name" . -}}
{{- $labels := include "ditto.labels" . -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-nginx-ingress-htpasswd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}-nginx-ingress-config
{{ $labels | indent 4 }}
type: Opaque
stringData:
  auth: |-
{{- if .Values.global.hashedBasicAuthUsers }}
  {{ range .Values.global.hashedBasicAuthUsers }}
    {{- . | indent 4 }}
  {{ end }}
{{- else }}
  {{- if (quote .Values.global.existingSecret | empty) }}
    {{ range $key, $value := .Values.global.basicAuthUsers }}
      {{- (htpasswd $value.user $value.password) | indent 4 }}
    {{ end }}
  {{- else }}
    {{- $secret := lookup "v1" "Secret" $.Release.Namespace .Values.global.existingSecret }}
    {{- if $secret }}
      {{- range $user, $password := $secret.data }}
        {{ htpasswd $user ($password | b64dec) | indent 4 }}
      {{- end }}
    {{- else}}
      {{- fail (printf "Missing provided existingSecret for basicAuthUsers: %s" .Values.global.existingSecret) }}
    {{- end }}
  {{ end }}
{{ end }}
---
{{- end }}
