# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- if and .Values.thingsSearch.podMonitor.enabled .Values.global.prometheus.port -}}
{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" -}}
---
kind: PodMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: {{ include "ditto.fullname" . }}-thingssearch
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}-thingssearch
{{ include "ditto.labels" . | indent 4 }}
spec:
  podMetricsEndpoints:
  - targetPort: {{ .Values.global.prometheus.port }}
    path: "/"
    {{- if .Values.thingsSearch.podMonitor.interval }}
    interval: {{ .Values.thingsSearch.podMonitor.interval }}
    {{- end }}
    {{- if .Values.thingsSearch.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ .Values.thingsSearch.podMonitor.scrapeTimeout }}
    {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ditto.name" . }}-thingssearch
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
{{- end }}
{{- end }}
