# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- if and .Values.thingsSearch.podDisruptionBudget.enabled (gt .Values.thingsSearch.replicaCount 1.0) -}}
{{- if and .Values.thingsSearch.podDisruptionBudget.minAvailable .Values.thingsSearch.podDisruptionBudget.maxUnavailable }}
{{- fail "thingsSearch.podDisruptionBudget cannot have both minAvailable and maxUnavailable set. Please set only one of them." }}
{{- end }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "ditto.fullname" . }}-thingssearch
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}-thingssearch
{{ include "ditto.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "ditto.name" . }}-thingssearch
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- if .Values.thingsSearch.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.thingsSearch.podDisruptionBudget.minAvailable }}
{{- else }}
  maxUnavailable: {{ .Values.thingsSearch.podDisruptionBudget.maxUnavailable }}
{{- end }}
{{- end }}
