version: '3.0'

services:
  mongodb:
    image: docker.io/mongo:3.4
    networks:
      default:
        aliases:
          - mongodb
    command: mongod --storageEngine wiredTiger --noscripting
    user: mongodb
    environment:
       TZ: Europe/Berlin

  policies:
    image: docker.io/eclipse/ditto-policies:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    entrypoint: sh -c "java -jar /opt/ditto/starter.jar"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError -Dditto.cluster.become-leader=true
      - IBM_JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError -Dditto.cluster.become-leader=true

  things:
    image: docker.io/eclipse/ditto-things:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    entrypoint: sh -c "sleep 10; java -jar /opt/ditto/starter.jar"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
      - IBM_JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError

  things-search:
    image: docker.io/eclipse/ditto-things-search:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    entrypoint: sh -c "sleep 15; java -jar /opt/ditto/starter.jar"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
      - IBM_JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError

  concierge:
    image: docker.io/eclipse/ditto-concierge:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
    entrypoint: sh -c "sleep 20; java -jar /opt/ditto/starter.jar"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
      - IBM_JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError

  connectivity:
    image: docker.io/eclipse/ditto-connectivity:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
      - concierge
    entrypoint: sh -c "sleep 30; java -jar /opt/ditto/starter.jar"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
      - IBM_JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError

  gateway:
    image: docker.io/eclipse/ditto-gateway:${DITTO_VERSION:-latest}
    networks:
      default:
        aliases:
          - ditto-cluster
    depends_on:
      - policies
      - concierge
    entrypoint: sh -c "sleep 40; java -jar /opt/ditto/starter.jar"
    ports:
      - "8081:8080"
    environment:
      - TZ=Europe/Berlin
      - INSTANCE_INDEX=1
      - BIND_HOSTNAME=0.0.0.0
      - ENABLE_DUMMY_AUTH=true
      - _JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError
      - IBM_JAVA_OPTIONS=-Xms256m -Xmx256m -Xss512k -XX:MaxMetaspaceSize=128m -XX:+ExitOnOutOfMemoryError

  swagger-ui:
    image: docker.io/swaggerapi/swagger-ui:v2.2.9
    volumes:
       - ../documentation/src/main/resources/openapi:/usr/share/nginx/html/openapi:ro
       - ../documentation/src/main/resources/images:/usr/share/nginx/html/images:ro
       - ./swagger-index.html:/usr/share/nginx/html/index.html:ro
    environment:
      - API_URL=/apidoc/openapi/ditto-api-1.yml

  nginx:
    image: docker.io/nginx:1.13-alpine
    volumes:
       - ./nginx.conf:/etc/nginx/nginx.conf:ro
       - ./nginx.htpasswd:/etc/nginx/nginx.htpasswd:ro
       - ./nginx-cors.conf:/etc/nginx/nginx-cors.conf:ro
       - ./index.html:/etc/nginx/html/index.html:ro
       - ../documentation/src/main/resources/images:/etc/nginx/html/images:ro
    ports:
      - "8080:80"
    depends_on:
      - gateway
      - swagger-ui
