{{- if .Values.concierge.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eclipse-ditto.fullname" . }}-concierge
  labels:
    app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-concierge
{{ include "eclipse-ditto.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.concierge.replicaCount }}
  strategy:
  {{- with .Values.concierge.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-concierge
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-concierge
        app.kubernetes.io/instance: {{ .Release.Name }}
        actorSystemName: {{ .Values.akka.actorSystemName }}
        {{- with .Values.concierge.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.global.prometheus.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/"
        prometheus.io/port: "{{ .Values.global.prometheus.port }}"
        {{- end }}
        checksum/mongodb-config: {{ include (print $.Template.BasePath "/mongodb-secret.yaml") . | sha256sum }}
        {{- with .Values.concierge.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "eclipse-ditto.serviceAccountName" . }}
      {{- end }}
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-concierge
          image: "{{ .Values.concierge.image.repository }}:{{ .Values.concierge.image.tag }}"
          imagePullPolicy: {{ .Values.concierge.image.imagePullPolicy }}
          command: ["java"]
          args:
          {{- if .Values.concierge.systemProps }}
            {{- toYaml .Values.concierge.systemProps | nindent 12 }}
          {{- end }}
            - "-jar"
            - "/opt/ditto/starter.jar"
          env:
            - name: POD_LABEL_SELECTOR
              value: "app.kubernetes.io/name=%s"
            - name: POD_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: INSTANCE_INDEX
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: DISCOVERY_METHOD
              value: "kubernetes-api"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: OPENJ9_JAVA_OPTIONS
              value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError{{ if .Values.dbconfig.concierge.ssl }} -Dorg.mongodb.async.type=netty{{ end }}"
            - name: MONGO_DB_SSL_ENABLED
              value: "{{ if .Values.dbconfig.concierge.ssl }}true{{ else }}false{{ end }}"
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "eclipse-ditto.fullname" . }}-mongodb-secret
                  key: concierge-uri
          {{- if .Values.global.prometheus.enabled }}
            - name: PROMETHEUS_PORT
              value: "{{ .Values.global.prometheus.port }}"
          {{- end }}
          {{- if .Values.concierge.extraEnv }}
            {{- toYaml .Values.concierge.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: remoting
              containerPort: {{ .Values.akka.remoting.port }}
              protocol: TCP
            - name: management
              containerPort: {{ .Values.akka.mgmthttp.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              port: management
              path: /ready
            initialDelaySeconds: {{ .Values.concierge.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.concierge.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.concierge.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.concierge.readinessProbe.failureThreshold }}
          livenessProbe:
            httpGet:
              port: management
              path: /alive
            initialDelaySeconds: {{ .Values.concierge.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.concierge.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.concierge.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.concierge.livenessProbe.failureThreshold }}
          resources:
            {{- toYaml .Values.concierge.resources | nindent 12 }}
      {{- with .Values.concierge.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.concierge.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.concierge.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
