---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.concierge.name }}
  labels:
    app: {{ .Values.concierge.name }}
    app.kubernetes.io/name: {{ .Values.concierge.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{.Chart.Version}}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.concierge.name }}
        actorSystemName: ditto-cluster
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.concierge.name }}
          image: "{{ .Values.concierge.image.repository }}:{{ .Values.concierge.image.tag }}"
          imagePullPolicy: {{ .Values.concierge.image.imagePullPolicy }}
          command: ["java"]
          args: ["-jar", "/opt/ditto/starter.jar"]
          ports:
            - name: akka-remoting
              containerPort: {{ .Values.akka.remoting.port }}
              protocol: TCP
            - name: akka-mgmt-http
              containerPort: {{ .Values.akka.mgmthttp.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.akka.mgmthttp.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.akka.remoting.port }}
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 4
          env:
            - name: K8S_NAMESPACE
              value: {{.Release.Namespace}}
            - name: INSTANCE_INDEX
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: DISCOVERY_METHOD
              value: "kubernetes-api"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: IBM_JAVA_OPTIONS
              value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError"
            - name: MONGO_DB_SSL_ENABLED
              value: "{{ .Values.mongodb.apps.concierge.ssl }}"
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: concierge-uri
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.connectivity.name }}
  labels:
    app: {{ .Values.connectivity.name }}
    app.kubernetes.io/name: {{ .Values.connectivity.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{.Chart.Version}}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.connectivity.name }}
        actorSystemName: ditto-cluster
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.connectivity.name }}
          image: "{{ .Values.connectivity.image.repository }}:{{ .Values.connectivity.image.tag }}"
          imagePullPolicy: {{ .Values.connectivity.image.imagePullPolicy }}
          command: ["java"]
          args: ["-jar", "/opt/ditto/starter.jar"]
          ports:
            - name: akka-remoting
              containerPort: {{ .Values.akka.remoting.port }}
              protocol: TCP
            - name: akka-mgmt-http
              containerPort: {{ .Values.akka.mgmthttp.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.akka.mgmthttp.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.akka.remoting.port }}
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 4
          env:
            - name: K8S_NAMESPACE
              value: {{.Release.Namespace}}
            - name: INSTANCE_INDEX
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: DISCOVERY_METHOD
              value: "kubernetes-api"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: IBM_JAVA_OPTIONS
              value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError"
            - name: MONGO_DB_SSL_ENABLED
              value: "{{ .Values.mongodb.apps.connectivity.ssl }}"
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: connectivity-uri
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.things.name }}
  labels:
    app: {{ .Values.things.name }}
    app.kubernetes.io/name: {{ .Values.things.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{.Chart.Version}}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.things.name }}
        actorSystemName: ditto-cluster
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.things.name }}
          image: "{{ .Values.things.image.repository }}:{{ .Values.things.image.tag }}"
          imagePullPolicy: {{ .Values.things.image.imagePullPolicy }}
          command: ["java"]
          args: ["-jar", "/opt/ditto/starter.jar"]
          ports:
            - name: akka-remoting
              containerPort: {{ .Values.akka.remoting.port }}
              protocol: TCP
            - name: akka-mgmt-http
              containerPort: {{ .Values.akka.mgmthttp.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.akka.mgmthttp.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.akka.remoting.port }}
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 4
          env:
            - name: K8S_NAMESPACE
              value: {{.Release.Namespace}}
            - name: INSTANCE_INDEX
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: DISCOVERY_METHOD
              value: "kubernetes-api"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: IBM_JAVA_OPTIONS
              value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError"
            - name: MONGO_DB_SSL_ENABLED
              value: "{{ .Values.mongodb.apps.things.ssl }}"
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: things-uri
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.search.name }}
  labels:
    app: {{ .Values.search.name }}
    app.kubernetes.io/name: {{ .Values.search.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{.Chart.Version}}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.search.name }}
        actorSystemName: ditto-cluster
    spec:
      containers:
        - name: {{ .Values.search.name }}
          image: "{{ .Values.search.image.repository }}:{{ .Values.search.image.tag }}"
          imagePullPolicy: {{ .Values.search.image.imagePullPolicy }}
          command: ["java"]
          args: ["-jar", "/opt/ditto/starter.jar"]
          ports:
            - name: akka-remoting
              containerPort: {{ .Values.akka.remoting.port }}
              protocol: TCP
            - name: akka-mgmt-http
              containerPort: {{ .Values.akka.mgmthttp.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.akka.mgmthttp.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.akka.remoting.port }}
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 4
          env:
            - name: K8S_NAMESPACE
              value: {{.Release.Namespace}}
            - name: INSTANCE_INDEX
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: DISCOVERY_METHOD
              value: "kubernetes-api"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: IBM_JAVA_OPTIONS
              value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError"
            - name: MONGO_DB_SSL_ENABLED
              value: "{{ .Values.mongodb.apps.searchDB.ssl }}"
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: searchDB-uri
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.policies.name }}
  labels:
    app: {{ .Values.policies.name }}
    app.kubernetes.io/name: {{ .Values.policies.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{.Chart.Version}}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.policies.name }}
        actorSystemName: ditto-cluster
    spec:
      containers:
        - name: {{ .Values.policies.name }}
          image: "{{ .Values.policies.image.repository }}:{{ .Values.policies.image.tag }}"
          imagePullPolicy: {{ .Values.policies.image.imagePullPolicy }}
          command: ["java"]
          args: ["-jar", "/opt/ditto/starter.jar"]
          ports:
            - name: akka-remoting
              containerPort: {{ .Values.akka.remoting.port }}
              protocol: TCP
            - name: akka-mgmt-http
              containerPort: {{ .Values.akka.mgmthttp.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.akka.mgmthttp.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.akka.remoting.port }}
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 4
          env:
            - name: K8S_NAMESPACE
              value: {{.Release.Namespace}}
            - name: INSTANCE_INDEX
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: DISCOVERY_METHOD
              value: "kubernetes-api"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: IBM_JAVA_OPTIONS
              value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError"
            - name: MONGO_DB_SSL_ENABLED
              value: "{{ .Values.mongodb.apps.policies.ssl }}"
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: policies-uri
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    app: {{ .Values.gateway.name }}
    app.kubernetes.io/name: {{ .Values.gateway.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{.Chart.Version}}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ .Values.gateway.name }}
        actorSystemName: ditto-cluster
    spec:
      containers:
        - name: {{ .Values.gateway.name }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.gateway.image.imagePullPolicy }}
          command: ["java"]
          args: ["-jar", "/opt/ditto/starter.jar"]
          ports:
            - name: akka-remoting
              containerPort: {{ .Values.akka.remoting.port }}
              protocol: TCP
            - name: akka-mgmt-http
              containerPort: {{ .Values.akka.mgmthttp.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.akka.mgmthttp.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.akka.remoting.port }}
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 4
          env:
            - name: K8S_NAMESPACE
              value: {{.Release.Namespace}}
            - name: ENABLE_DUMMY_AUTH
              value: "true"
            - name: INSTANCE_INDEX
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP
            - name: DISCOVERY_METHOD
              value: "kubernetes-api"
            - name: TZ
              value: "{{ .Values.global.timezone }}"
            - name: IBM_JAVA_OPTIONS
              value: "-XX:MaxRAMPercentage=80 -XX:InitialRAMPercentage=40 -XX:+ExitOnOutOfMemoryError"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.gateway.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{.Chart.Version}}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ .Values.gateway.name }}
