{{- if .Values.nginx.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: ditto
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.nginx.version }}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.service.loadBalancerIP.enabled }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP.address }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.nginx.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.name }}
  labels:
    app: {{ .Values.nginx.name }}
    app.kubernetes.io/name: {{ .Values.nginx.name }}
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/version: "{{ .Values.nginx.version }}"
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.nginx.name }}
  replicas: {{ .Values.nginx.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Values.nginx.name }}
    spec:
      containers:
        - name: {{ .Values.nginx.name }}
          image: docker.io/nginx:{{ .Values.nginx.version }}-alpine
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-htpasswd
              mountPath: /etc/nginx/nginx.htpasswd
              subPath: nginx.htpasswd
            - name: nginx-cors
              mountPath: /etc/nginx/nginx-cors.conf
              subPath: nginx-cors.conf
            - name: nginx-index
              mountPath: /etc/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
        - name: nginx-htpasswd
          configMap:
            name: nginx-htpasswd
        - name: nginx-cors
          configMap:
            name: nginx-cors
        - name: nginx-index
          configMap:
            name: nginx-index
{{- if .Values.nginx.rootAccess }}
      securityContext:
        runAsUser: 0
{{- end }}
{{- end }}