{{- if and .Values.policies.podDisruptionBudget.enabled (gt .Values.policies.replicaCount 1.0) -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "eclipse-ditto.fullname" . }}-policies
  labels:
    app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-policies
{{ include "eclipse-ditto.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-policies
      app.kubernetes.io/instance: {{ .Release.Name }}
  minAvailable: {{ .Values.policies.podDisruptionBudget.minAvailable }}
{{- end }}
