{{- if .Values.swaggerui.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eclipse-ditto.fullname" . }}-swaggerui
  labels:
    app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-swaggerui
{{ include "eclipse-ditto.labels" . | indent 4 }}
spec:
spec:
  replicas: {{ .Values.swaggerui.replicaCount }}
  strategy:
  {{- with .Values.swaggerui.updateStrategy }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-swaggerui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eclipse-ditto.name" . }}-swaggerui
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.swaggerui.additionalLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- with .Values.swaggerui.additionalAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}-swaggerui
          image: "{{ .Values.swaggerui.image.repository }}:{{ .Values.swaggerui.image.tag }}"
          imagePullPolicy: {{ .Values.swaggerui.image.imagePullPolicy }}
          env:
          {{- if .Values.swaggerui.extraEnv }}
            {{- toYaml .Values.swaggerui.extraEnv | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: swagger-ui-api
              mountPath: /usr/share/nginx/html/openapi
      volumes:
        - name: swagger-ui-api
          configMap:
            name: {{ include "eclipse-ditto.fullname" . }}-swaggerui
{{- if .Values.swaggerui.rootAccess }}
      securityContext:
        runAsUser: 0
{{- end }}
{{- end }}
